USE_CAMERA_STUB := true

DEVICE_DIR := device/lenovo/TB3_710F

# inherit from the proprietary version
-include vendor/lenovo/TB3_710F/BoardConfigVendor.mk

# Additional
TARGET_SPECIFIC_HEADER_PATH := $(DEVICE_DIR)/include

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := mt8127
TARGET_BOARD_PLATFORM_GPU := mali-450mp4
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true
ARCH_ARM_HAVE_NEON := true
TARGET_BOOTLOADER_BOARD_NAME := mt8127
# Tzul's 3.0.2 TWRP needs this for flashing (updater-script assert check)
TARGET_OTA_ASSERT_DEVICE := TB3-710F

# Kernel

BOARD_KERNEL_CMDLINE := androidboot.selinux=permissive initcall_debug ignore_loglevel trace_event=block,ext4 trace_buf_size=64M trace_event=sched_wakeup,sched_switch,sched_blocked_reason,sched_cpu_hotplug
BOARD_KERNEL_BASE := 0x80000000
BOARD_KERNEL_PAGESIZE := 2048

BUILD_KERNEL_FROM_SOURCE := false
ifeq ($(BUILD_KERNEL_FROM_SOURCE),true)
    TARGET_KERNEL_SOURCE := kernel/lenovo/TB3_710F
    TARGET_KERNEL_CONFIG := hq8127_tb_b2b_l_defconfig
    BOARD_KERNEL_IMAGE_NAME := Image
else
# obtain zImage from stock boot.img (using abootimg, e.g.)
    TARGET_PREBUILT_KERNEL := $(DEVICE_DIR)/zImage
endif

# Partitions

BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1696440320
BOARD_USERDATAIMAGE_PARTITION_SIZE := 5436866560
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := false
BOARD_CACHEIMAGE_PARTITION_SIZE := 268435456
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_FLASH_BLOCK_SIZE := 131072

#RECOVERY_VARIANT := twrp

BOARD_HAS_NO_SELECT_BUTTON := true

# System ROM configuration
#LOCAL_DEX_PREOPT := true
#PRODUCT_DEX_PREOPT_BOOT_FLAGS := true
#PRODUCT_DEX_PREOPT_DEFAULT_FLAGS := true
#PRODUCT_DEX_PREOPT_MODULE_CONFIGS := true

# MTK Hardware
BOARD_USES_MTK_HARDWARE := true
BOARD_HAS_MTK_HARDWARE := true
MTK_HARDWARE := true
BLOCK_BASED_OTA := false
BOARD_HAS_MTK := true
MTK_HWC_CHIP := mt8127
MTK_HWC_SUPPORT := true
MTK_WFD_SUPPORT := true
MTK_PQ_SUPPORT := true
MTK_ION_SUPPORT := true
MTK_HDMI_SUPPORT := false
MTK_SENSOR_SUPPORT := true

# Flags -- added from Tab2A710F by szazs@mm.bme.hu
TARGET_GLOBAL_CFLAGS += -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -DMTK_HARDWARE -mfpu=neon -mfloat-abi=softfp
COMMON_GLOBAL_CFLAGS += -DREFRESH_RATE=60
COMMON_GLOBAL_CFLAGS += -DMTK_HARDWARE
COMMON_GLOBAL_CFLAGS += -DADD_LEGACY_ACQUIRE_BUFFER_SYMBOL
COMMON_GLOBAL_CFLAGS += -DNO_SECURE_DISCARD

# Display
USE_OPENGL_RENDERER := true
BOARD_EGL_CFG := device/lenovo/TB3_710F/configs/egl.cfg
TARGET_USES_C2D_COMPOSITION := true
TARGET_USES_OVERLAY := true
TARGET_USES_ION := true
TARGET_DISPLAY_USE_RETIRE_FENCE := true
MAX_EGL_CACHE_KEY_SIZE := 12*1024
MAX_EGL_CACHE_SIZE := 1024*1024
TARGET_SCREEN_HEIGHT := 1024
TARGET_SCREEN_WIDTH := 600

# Surfaceflinger optimization for VD surfaces
TARGET_FORCE_HWC_FOR_VIRTUAL_DISPLAYS := true
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3

# WIFI
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_mt66xx
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_mt66xx
WIFI_DRIVER_FW_PATH_PARAM:="/dev/wmtWifi"
WIFI_DRIVER_FW_PATH_STA:=STA
WIFI_DRIVER_FW_PATH_AP:=AP
WIFI_DRIVER_FW_PATH_P2P:=P2P
WIFI_HIDL_FEATURE_AWARE := true

# system.prop
TARGET_SYSTEM_PROP := device/lenovo/TB3_710F/system.prop

# BT
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_MTK := true
BOARD_BLUETOOTH_DOES_NOT_USE_RFKILL := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := $(DEVICE_DIR)/bluetooth

# libxlog
TARGET_LDPRELOAD += libxlog.so

# SELinux
#BOARD_SEPOLICY_DIRS := \
#       $(DEVICE_DIR)/sepolicy

#BOARD_SEPOLICY_UNION := \
#        seapp_contexts  \
#        service_contexts \
#        property_contexts \
#        file_contexts

DEVICE_RESOLUTION := 1024x600
#RECOVERY_FSTAB_VERSION := 1
TARGET_RECOVERY_FSTAB := device/lenovo/TB3_710F/recovery/root/recovery.fstab
TARGET_RECOVERY_INITRC := device/lenovo/TB3_710F/recovery/root/init.rc
#BOARD_HAS_NO_REAL_SDCARD := false
#TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/class/android_usb/android0/f_mass_storage/lun/file
#RECOVERY_SDCARD_ON_DATA := true 
TARGET_USES_LOGD := true
